name: Gold 24h2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 23 * * *'   # 06:50 giờ Hà Nội
    - cron: '50 3 * * *'    # 10:50 giờ Hà Nội
    - cron: '50 7 * * *'    # 14:50 giờ Hà Nội
    - cron: '50 10 * * *'   # 17:50 giờ Hà Nội
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run script
      run: |
        python gold.py  